#https://github.com/travis-ci/travis-ci/issues/5805
before_install:
  - rm ~/.m2/settings.xml
#
#  in case of ant this was needed
#  - sudo apt-get install ant-optional
#
# https://docs.travis-ci.com/user/languages/java/
language: java
jdk:
  - openjdk11

#
env:
  - TOPJAVA_ROOT=$TRAVIS_BUILD_DIR

script:
  - mvn clean test
#
#notifications:
#  email:
#    recipients:
#      - davide.basile@isti.cnr.it